### ISSUE TITLE
Readme out of date

### ISSUE THREAD

**Issue by msik314** [godotengine/godot-headers#18]
The test script provided in the README file wil no longer compile.
`godot_string_new_unicode_data(&s, L"Hello World", 11);` does not seem to be in the API at all anymore.
Actually, the readme script no longer uses the most up to date API.  If you get it to compile, Godot will just crash when loading it.

**Comment by bevinhex** [comment]
Yeah, was trying to get my hands on gdnative, but a little frustrated to get a helloworld up and running

**Comment by lane-s** [comment]
It seems that https://github.com/GodotNativeTools/GDNative-demos/tree/master/c/SimpleDemo is a better source for getting up and running with GDNative. I may be wrong about that since I'm just trying to get started myself, but the instructions here definitely did not work for me.

**Comment by BastiaanOlij** [comment]
Since August the readme has been updated and as far as I can tell should work. The only thing currently missing are Windows compile commands. I'll dig those  up and add them when I have a free minute.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Still looking for those Windows commands :D

**Comment by Banderi** [comment]
I don't know how relevant or how helpful this could be, but I was really frustrated as well with not being able to compile with CLion on Windows (no SCons support) so I thought I'd leave this here. Here is what I managed to find that allowed me to compile the [plain C example project](https://docs.godotengine.org/en/3.1/tutorials/plugins/gdnative/gdnative-c-example.html), with standard CMakeLists.txt:
```CMake
cmake_minimum_required(VERSION 3.17)
project(GodotNeuralNetworkTests2)

set(CMAKE_CXX_STANDARD 14)
include_directories(${PROJECT_SOURCE_DIR}/godot-headers)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ../project/gdnative/windows)

add_library(simple SHARED src/simple.c)
```

**Comment by BastiaanOlij** [comment]
@Banderi hmm, that would be good to add to an example here: https://github.com/godotengine/gdnative-demos

This repo itself is just meant as a mirror for the GDNative header files. Examples are worked out either in the official documentation or in the demos repo.

**Comment by BastiaanOlij** [comment]
Closing this issue as the issue itself I believe has been resolved ages ago. 
A full and more detailed example can be found here: https://docs.godotengine.org/en/stable/tutorials/plugins/gdnative/gdnative-c-example.html
