### ISSUE TITLE
godot_rect2 has no GODOT_RECT2_SIZE

### ISSUE THREAD

**Issue by KaneTW** [godotengine/godot-headers#20]
magic numbers are a pain, constants are easier to work with when writing bindings that need to malloc stuff

**Comment by BastiaanOlij** [comment]
We added the optional define GODOT_CORE_API_GODOT_RECT2_TYPE_DEFINED awhile ago so you can do:

```
#define GODOT_CORE_API_GODOT_RECT2_TYPE_DEFINED
typedef union {
	//Force struct to be classified as INTEGER by System V AMD64 ABI.
	uint8_t _dont_touch_that[16];
	struct {
		godot_vector2 position;
		godot_vector2 size;
	};
} godot_rect2;
#include <gdnative_api_struct.gen.h>
```

**Comment by aaronfranke** [comment]
Is this still relevant in the current master branch?

**Comment by BastiaanOlij** [comment]
Unless there is a specific use case someone can think off, I think time has proven the current implementation has been happily adopted by the community. Closing this as an old issue.
