### ISSUE TITLE
Create documentation for binding authors

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot-headers#3]
Write down how to create language bindings using the GDNative API.

**Comment by malte-v** [comment]
I would really like to create bindings for the Crystal language and I don't know where to start. Is anybody currently working on this?

**Comment by malte-v** [comment]
This issue seems fairly old. I'll create a new one.

**Comment by karroffel** [comment]
No need, it's just not a small topic and I haven't been doing much with Godot or GDNative in a while, sorry :confused:

**Comment by BastiaanOlij** [comment]
Documentation can be found here: https://docs.godotengine.org/en/stable/tutorials/plugins/gdnative/gdnative-c-example.html
