### ISSUE TITLE
Anybody knows how to achieve cooroutines in GDNative? Aka yield(user, signal) from gdscript

### ISSUE THREAD

**Issue by OliPerraul** [godotengine/godot-headers#33]
Is there a way to achieve coroutines in GDNative? Or the equivalent yield from gdscript or ToSignal from C#

**Comment by BastiaanOlij** [comment]
@OliPerraul sorry for no reactions on this. I remember discussing this with @karroffel on IRC a little while ago. GDScript yields seem to be a different breed where code is actually split up if I understood correctly.
Not sure how you would reproduce that behavior in GDNative as it isn't a yield in the normal multi-threaded way.

**Comment by girng** [comment]
@willnationsdev might be able to help / chime in on this question as well

**Comment by BastiaanOlij** [comment]
I'm closing this as an old issue even though it is unresolved. To my knowledge this is not possible in GDNative. The yield system in GDScript basically splits the code in two with a callback, you'd manually need to break your code up like that, it's not a true yield in the multitasking sense of the feature.
