### ISSUE TITLE
Missing header file for AtlasTexture 

### ISSUE THREAD

**Issue by t-mullen** [godotengine/godot-headers#45]
It seems the header file `AtlasTexture.hpp` is missing from this repository. The binding for it is in `api.json`.

Is there any reason AtlasTexture does not have complete bindings?

**Comment by BastiaanOlij** [comment]
The godot_headers repository only has the core classes for the GDNative interface as part of it. If you want full bindings of all classes in Godot you need to use the godot-cpp bindings library.
The API.JSON file is only included in this repository as all the different binding libraries use this repo as their base and its a nice convenient place to have it.

**Comment by t-mullen** [comment]
godot-cpp is also missing the AtlasTexture bindings, should I reopen this issue in that repository?

**Comment by BastiaanOlij** [comment]
I'm closing this as an old issue. `AtlasTexture` can be found in the `api.json` so bindings for it should be created. Testing was probably done with an outdated `api.json` at the time. If this is still a problem it needs to be resolved in Godot itself to ensure `AtlasTexture` is exposed properly.
