### ISSUE TITLE
Tag specific commits for each Godot stable version

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot-headers#53]
Follow-up on #24, which added dedicated branches for stable Godot versions, matching the Godot repository.

In 3.1.1 we broke GDNative compatibility with 3.1 to fix a security issue, so the need to tag stable version arises. I propose to use the same convention as the Godot repository and to tag specific commits from the stable branches with matching `3.1-stable`, `3.1.1-stable`, etc. tags.

IINM, 489db27 would be `3.1-stable` and 98ee8259 would be `3.1.1-stable`.
It might be worth tagging 3.0.x versions in the `3.0` branch too (it's OK if several tags share the same commit if no update happened in the meantime).

I can do this if we agree on this versioning. CC @karroffel @BastiaanOlij 

I'm also working on an update of http://docs.godotengine.org/en/latest/tutorials/plugins/gdnative/gdnative-c-example.html which includes some misleading information. Once we have tags, I would suggest that this tutorial makes people checkout the actual tag matching their Godot version, instead of assuming compatibility.

**Comment by akien-mga** [comment]
BTW, I'd suggest to do the same for the godot-cpp repo. I see that it already has some `0.1.0` and `1.0.0` pre-releases: https://github.com/GodotNativeTools/godot-cpp/releases

Do those make semantic sense, and if not should we remove them and replace them by the matching Godot versions? Or if they do make sense, are there more versions that should be tagged? We could then tag Godot versions with a `godot-` prefix, e.g. `godot-3.1.1-stable`, to make it clear that it's about the engine and not bindings version.

**Comment by akien-mga** [comment]
> I can do this if we agree on this versioning.

Actually I can't as I don't have Write access to this repo :P

**Comment by karroffel** [comment]
I added the tags `godot-3.1-stable` and `godot-3.1-stable`

**Comment by akien-mga** [comment]
@karroffel The `godot-3.1-stable` tag is good, but the other one is wrongly named with an extra dot: `godot-3.1.1.-stable`.

**Comment by karroffel** [comment]
Oops, will fix!

**Comment by Pewsplosions** [comment]
Will there be a tag for 3.2 now that its the latest stable branch? Doing the GDNative tutorial and it says it is best to use a version of the headers with matching tag to version of Godot I am using. But there doesn't seem to be a 3.2 at the moment.

**Comment by akien-mga** [comment]
This can be closed, releases have properly been tagged from 3.1-stable onward: https://github.com/godotengine/godot-headers/tags
