### ISSUE TITLE
Include nullability information

### ISSUE THREAD

**Issue by raniejade** [godotengine/godot-headers#65]
It will be nice to have a field that denotes if the returned type of a property or method can be null. This is useful for language bindings that support nullable types (i.e Kotlin).

**Comment by aaronfranke** [comment]
Ideally what we want is to let the core API provide this information. Therefore, this depends on https://github.com/godotengine/godot-proposals/issues/162, since it will be easier to implement this for GDNative after it's supported in GDScript.

**Comment by BastiaanOlij** [comment]
@raniejade  I'm for closing this issue. This is not a `godot-headers` issue but something that needs to be supported in Godot itself first (as per proposal @aaronfranke is pointing at).

In the meanwhile I would make the assumption that all methods that return objects can return either a null pointer or null reference. It's pretty standard in the Godot core to return this in failure situations.
