### ISSUE TITLE
wchar.h file does not exists and while compilling for Mac it generates error

### ISSUE THREAD

**Issue by JezSonic** [godotengine/godot-headers#68]
In file included from simple.c:1:
In file included from ../../godot_headers\gdnative_api_struct.gen.h:5:
In file included from ../../godot_headers\gdnative/gdnative.h:141:
../../godot_headers\gdnative/string.h:39:10: fatal error: 'wchar.h' file not found
#include <wchar.h>
         ^
1 error generated

Command, i used:
clang -std=c11 -fPIC -c -I../../godot_headers simple.c -o simple.os
clang -dynamiclib simple.os -o ../bin/libsimple.dylib

I am using the newest version of Godot Headers and Godot 3.2

**Comment by follower** [comment]
I have `wchar.h` located in ` /usr/include/wchar.h`.

You may need to install XCode or CommandLineTools which contain an SDK in order to obtain the file.

**Comment by BastiaanOlij** [comment]
Is this still an issue? Sounds indeed like an SDK installation problem.

**Comment by akien-mga** [comment]
Indeed, `wchar.h` should be in the default include path with a properly configured build environment. That's not Godot specific, there are likely many StackOverflow or forum topics covering how to debug and fix this for macOS.
