### ISSUE TITLE
Built-in GDScript functions

### ISSUE THREAD

**Issue by vonagam** [godotengine/godot-headers#91]
This is not a bug, just a question.

There are multiple issues about `yield` which has obviously a gdscript specific implementation, but what about [others](https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#methods)?

Almost one hundred useful methods that are currently unavailable for native bindings. Looking at C++ and C# adapters it seems like you have to write your own implementation to match the api...

(I guess for now i'll have to create some singleton that exposes all those methods (which do not have varargs) and then simply "call" them (not the most performant way, but something).)

How hard it would be to expose those methods and are there any plans to do so?

**Comment by akien-mga** [comment]
This was already changed for Godot 4.0 with most of these methods now being exposed in `@GlobalScope` instead of `@GDScript`.

**Comment by vonagam** [comment]
Thanks.
